package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"sync"
	"time"
)

var mut sync.Mutex

func main() {
	var wg sync.WaitGroup
	file, err10 := os.Create("economic_llm.txt")
	if err10 != nil {
		fmt.Println(err10)
	}

	fmt.Println("initializing crypto_data")
	var list_functions = []string{"REAL_GDP", "CPI", "REAL_GDP_PER_CAPITA", "INFLATION", "RETAIL_SALES", "DURABLES", "UNEMPLOYMENT", "NONFARM_PAYROLL"}
	var number_of_functions = []int{}
	for i := 0; i < len(list_functions); i++ {
		wg.Add(1)
		function_name := list_functions[i]
		go get_economic_data(function_name, &wg, file)
		number_of_functions = append(number_of_functions, i)
		time.Sleep(time.Millisecond * 200)

	}
	wg.Wait()
	fmt.Println(number_of_functions)
}
func get_economic_data(func_name string, wg *sync.WaitGroup, file *os.File) {
	url := fmt.Sprintf("https://alpha-vantage.p.rapidapi.com/query?interval=5min&function=%s&symbol=MSFT&datatype=json&output_size=compact", func_name)
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		fmt.Println(err)
	}
	req.Header.Add("X-RapidAPI-Key", "a36ccd5d62mshee86e99fbcb9664p11139ejsn7777332728b5")
	req.Header.Add("X-RapidAPI-Host", "alpha-vantage.p.rapidapi.com")

	response, err3 := http.DefaultClient.Do(req)
	if err3 != nil {
		fmt.Println(err)
	}
	databytes, err4 := io.ReadAll(response.Body)
	if err4 != nil {
		fmt.Println(err)
	}
	type AutoGenerated struct {
		Name     string `json:"name"`
		Interval string `json:"interval"`
		Unit     string `json:"unit"`
		Data     []struct {
			Date  string `json:"date"`
			Value string `json:"value"`
		} `json:"data"`
	}
	fmt.Println(string(databytes))
	defer response.Body.Close()
	mut.Lock()
	var jsonunfolded AutoGenerated
	err2 := json.Unmarshal(databytes, &jsonunfolded)
	if err2 != nil {
		fmt.Println(err2)
	}
	fmt.Println(jsonunfolded)

	data := jsonunfolded.Data
	first_year := data[0]
	second_year := data[1]
	third_year := data[2]
	date := first_year.Date
	value := first_year.Value
	val2 := second_year.Value
	date2 := second_year.Date
	val3 := third_year.Value
	date3 := third_year.Date
	economic_context := fmt.Sprintf("the %s for %s is %s, the %s for %s is %s, the %s for %s is %s", func_name, date, value, func_name, date2, val2, func_name, date3, val3)

	io.WriteString(file, economic_context)
	mut.Unlock()
	wg.Done()
}
